# Welcome to Jekyll!

# Website settings
title: "Blockchain.Brussels"
description: "The local contact in Brussels for Bitcoin and Blockchain"
keywords: "Brussels, Bitcoin, Blockchain"
baseurl: "/"
url: "http://www.blockchain.brussels"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Fred'
  first_name: 'Frederik'
  last_name: 'Rousseau'
  email: 'fred@linox.be'
  #facebook_username: 'jiakunnj'
  github_username: 'LinoxBE'
  avatar: 'static/img/landing/FrederikR.jpg'
  desc: '“I’m Not a Genius, Just a Tremendous Bundle of Experience" (R. Buckminster Fuller)'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: linoxbe
  public_key: tj2Mffffffffff

# share
bshare:
  #uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  #id: UA-73784599-1

# growingIO
gio:
  #id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
